name: Docker Image CI

    on:
      push:
        branches:
          - dev
          - main
          - feat/ci
      pull_request:
        branches: 
          - dev
          - main

    jobs:
      deploy:
        runs-on: ubuntu-latest    
        steps:
          name: Checkout repository
          uses: actions/checkout@v4

          name: start application 
          run: docker compose up -d
